version: "3.8"
services:
  server:
    build: server/
    ports:
      - "3089:8000"
    networks:
      - mynetwork
  client:
    build: client/
    networks:
      - mynetwork
  redis:
    image: redis
    ports:
      - "6371:6379"
    networks:
      - mynetwork
networks:
  mynetwork: